# Generated by Django 5.2.11 on 2026-02-06 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("SELECCION", "En seleccion"),
                            ("CONTRATO_APROB", "Contrato aprobado"),
                            ("PROC_SEL_APROB", "Proceso seleccion aprobado"),
                            ("DESPACHADO", "Despachado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="DISPONIBLE",
                        max_length=30,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nit", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("direccion", models.CharField(blank=True, default="", max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("PROCESO_SELECCION", "Proceso de seleccion abierto"),
                            ("CONTRATO_NULO", "Contrato nulo"),
                            ("CONTRATADO", "Contratado"),
                        ],
                        default="DISPONIBLE",
                        max_length=30,
                    ),
                ),
                (
                    "capacidad_cupos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Numero de cupos disponibles para aprendices",
                    ),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono de contacto de la empresa",
                        max_length=30,
                    ),
                ),
                (
                    "correo_contacto",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Correo de contacto de la empresa",
                        max_length=254,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aprendiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo_identificacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("TI", "Tarjeta de Identidad"),
                            ("CE", "Cédula de Extranjería"),
                            ("PA", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=20,
                    ),
                ),
                (
                    "numero_identificacion",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("direccion", models.CharField(blank=True, default="", max_length=200)),
                (
                    "ficha",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de ficha del aprendiz",
                        max_length=20,
                    ),
                ),
                (
                    "programa_formacion",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Programa de formación del aprendiz",
                        max_length=200,
                    ),
                ),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("PROCESO_SELECCION", "Proceso de selección"),
                            (
                                "PROCESO_SELECCION_ABIERTO",
                                "Proceso de selección abierto",
                            ),
                            ("CONTRATO_NO_REGISTRADO", "Contrato no registrado"),
                            ("CONTRATADO", "Contratado"),
                            (
                                "INHABILITADO_POR_ACTUALIZACION",
                                "Inhabilitado por actualización",
                            ),
                        ],
                        default="DISPONIBLE",
                        max_length=30,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                (
                    "fecha_ultima_actividad",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "empresa_actual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plataforma.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ESTUDIANTE", "Estudiante"),
                            ("TRABAJADOR", "Trabajador/Admin"),
                            ("FUNCIONARIO_SENA", "Funcionario SENA"),
                        ],
                        default="ESTUDIANTE",
                        max_length=20,
                    ),
                ),
                (
                    "aprendiz",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plataforma.aprendiz",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_postulacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "En proceso de selección"),
                            (
                                "PROCESO_SELECCION_ABIERTO",
                                "Proceso de selección abierto",
                            ),
                            ("CONTRATO_NO_REGISTRADO", "Contrato no registrado"),
                            ("CONTRATADO", "Contratado"),
                            ("DISPONIBLE", "Disponible"),
                        ],
                        default="PENDIENTE",
                        max_length=30,
                    ),
                ),
                (
                    "observacion_aprendiz",
                    models.TextField(
                        blank=True, default="", help_text="Observación del aprendiz"
                    ),
                ),
                (
                    "observacion_empresa",
                    models.TextField(
                        blank=True, default="", help_text="Observación de la empresa"
                    ),
                ),
                (
                    "fecha_estado_actualizado",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha del último cambio de estado",
                        null=True,
                    ),
                ),
                (
                    "aprendiz_dio_respuesta",
                    models.BooleanField(
                        default=False, help_text="¿El aprendiz dejó observación?"
                    ),
                ),
                (
                    "empresa_dio_respuesta",
                    models.BooleanField(
                        default=False, help_text="¿La empresa dejó observación?"
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plataforma.aprendiz",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plataforma.empresa",
                    ),
                ),
            ],
            options={
                "unique_together": {("aprendiz", "empresa")},
            },
        ),
        migrations.CreateModel(
            name="HistorialPostulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(blank=True, max_length=20)),
                ("estado_nuevo", models.CharField(max_length=20)),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postulacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="plataforma.postulacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(max_length=30)),
                ("estado_nuevo", models.CharField(max_length=30)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="plataforma.solicitud",
                    ),
                ),
            ],
        ),
    ]
