# Generated by Django 5.2.11 on 2026-02-17 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, db_index=True, unique=True)),
                ('total_aprendices', models.IntegerField(default=0)),
                ('total_empresas', models.IntegerField(default=0)),
                ('aprendices_activos', models.IntegerField(default=0)),
                ('empresas_activas', models.IntegerField(default=0)),
                ('total_postulaciones', models.IntegerField(default=0)),
                ('postulaciones_nuevas', models.IntegerField(default=0)),
                ('postulaciones_seleccionadas', models.IntegerField(default=0)),
                ('postulaciones_rechazadas', models.IntegerField(default=0)),
                ('postulaciones_pendientes', models.IntegerField(default=0)),
                ('tasa_conversion', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de postulaciones seleccionadas', max_digits=5)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetricaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('CONTADOR', 'Contador'), ('PROMEDIO', 'Promedio'), ('PORCENTAJE', 'Porcentaje'), ('TIEMPO', 'Tiempo')], max_length=50)),
                ('valor', models.FloatField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'En proceso de selección'), ('PROCESO_SELECCION_ABIERTO', 'Proceso de selección abierto'), ('SELECCIONADO', 'Seleccionado'), ('RECHAZADO', 'Rechazado'), ('CONTRATO_NO_REGISTRADO', 'Contrato no registrado'), ('CONTRATADO', 'Contratado'), ('DISPONIBLE', 'Disponible')], default='PENDIENTE', max_length=30),
        ),
        migrations.CreateModel(
            name='CartaFechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_propuesta', models.DateField()),
                ('fecha_fin_propuesta', models.DateField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('salario_propuesto', models.DecimalField(decimal_places=2, help_text='Salario mensual propuesto', max_digits=10)),
                ('tipo_contrato', models.CharField(choices=[('PRACTICA', 'Práctica'), ('CONTRATO_APRENDIZAJE', 'Contrato de aprendizaje'), ('CONTRATO_TERMINO_FIJO', 'Contrato a término fijo'), ('CONTRATO_INDEFINIDO', 'Contrato indefinido')], default='CONTRATO_APRENDIZAJE', max_length=50)),
                ('cargo_ofrecido', models.CharField(help_text='Cargo o puesto ofrecido', max_length=200)),
                ('descripcion_actividades', models.TextField(help_text='Descripción de las actividades a realizar')),
                ('lugar_trabajo', models.CharField(help_text='Lugar o sede de trabajo', max_length=200)),
                ('horario_trabajo', models.CharField(help_text='Horario de trabajo', max_length=100)),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios adicionales ofrecidos')),
                ('seguro_medico', models.BooleanField(default=False, help_text='Incluye seguro médico')),
                ('transporte', models.BooleanField(default=False, help_text='Incluye auxilio de transporte')),
                ('alimentacion', models.BooleanField(default=False, help_text='Incluye auxilio de alimentación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Contrato completado')], default='PENDIENTE', max_length=30)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_aprobacion', models.TextField(blank=True, help_text='Comentarios del funcionario al aprobar/rechazar')),
                ('aprendiz_acepta', models.BooleanField(blank=True, help_text='El aprendiz aceptó la propuesta', null=True)),
                ('fecha_aceptacion_aprendiz', models.DateTimeField(blank=True, null=True)),
                ('comentarios_aprendiz', models.TextField(blank=True, help_text='Comentarios del aprendiz')),
                ('carta_propuesta', models.FileField(blank=True, help_text='Carta de propuesta oficial de la empresa', null=True, upload_to='cartas_contrato/')),
                ('documento_empresa', models.FileField(blank=True, help_text='Documentación adicional de la empresa', null=True, upload_to='documentos_empresa/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_fechas', to='plataforma.aprendiz')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_fechas', to='plataforma.empresa')),
                ('funcionario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartas_aprobadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carta de Fechas',
                'verbose_name_plural': 'Cartas de Fechas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMPRESA_A_APRENDIZ', 'Empresa califica a Aprendiz'), ('APRENDIZ_A_EMPRESA', 'Aprendiz califica a Empresa')], max_length=20)),
                ('puntuacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='plataforma.postulacion')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('postulacion', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='PromedioCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APRENDIZ', 'Aprendiz'), ('EMPRESA', 'Empresa')], max_length=10)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_calificaciones', models.IntegerField(default=0)),
                ('aprendiz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promedio_calificacion', to='plataforma.aprendiz')),
                ('empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promedio_calificacion', to='plataforma.empresa')),
            ],
            options={
                'unique_together': {('tipo', 'aprendiz', 'empresa')},
            },
        ),
    ]
